### PR TITLE
Added 'provides :vagrant_cluster' to fix Chef 13 compatibility

### PR DESCRIPTION
**Pull request by imriss**
Added 'provides :vagrant_cluster' to make it compatible with Chef 13 (and remove warning if Chef <13).

### CODE REVIEW

**Comment by tas50** [comment]
@imriss Can you sign that last commit off for the DCO so we can merge this in?

**Comment by imriss** [comment]
@tas50 done. Sorry, I made the change via web interface.

**Comment by tas50** [comment]
Thanks!

**Comment by tas50** [comment]
I pushed this up in 0.12

**Comment by imriss** [comment]
Thanks!

**Pull request merged**
